// NCERT curriculum seed — Subjects and their chapter-level Topics for grades
// 6–10. This is a starting catalog: it is fully editable in the Content Studio,
// and should be verified against the exact NCERT edition in use (the 2023–24
// rationalised textbooks differ in places).

export interface SeedTopic {
  grade: number;
  name: string;
}
export interface SeedSubject {
  name: string;
  topics: SeedTopic[];
}

const mathematics: SeedTopic[] = [
  // Grade 6
  { grade: 6, name: "Knowing Our Numbers" },
  { grade: 6, name: "Whole Numbers" },
  { grade: 6, name: "Playing with Numbers" },
  { grade: 6, name: "Basic Geometrical Ideas" },
  { grade: 6, name: "Understanding Elementary Shapes" },
  { grade: 6, name: "Integers" },
  { grade: 6, name: "Fractions" },
  { grade: 6, name: "Decimals" },
  { grade: 6, name: "Data Handling" },
  { grade: 6, name: "Mensuration" },
  { grade: 6, name: "Algebra" },
  { grade: 6, name: "Ratio and Proportion" },
  { grade: 6, name: "Symmetry" },
  { grade: 6, name: "Practical Geometry" },
  // Grade 7
  { grade: 7, name: "Integers" },
  { grade: 7, name: "Fractions and Decimals" },
  { grade: 7, name: "Data Handling" },
  { grade: 7, name: "Simple Equations" },
  { grade: 7, name: "Lines and Angles" },
  { grade: 7, name: "The Triangle and its Properties" },
  { grade: 7, name: "Congruence of Triangles" },
  { grade: 7, name: "Comparing Quantities" },
  { grade: 7, name: "Rational Numbers" },
  { grade: 7, name: "Perimeter and Area" },
  { grade: 7, name: "Algebraic Expressions" },
  { grade: 7, name: "Exponents and Powers" },
  { grade: 7, name: "Symmetry" },
  { grade: 7, name: "Visualising Solid Shapes" },
  // Grade 8
  { grade: 8, name: "Rational Numbers" },
  { grade: 8, name: "Linear Equations in One Variable" },
  { grade: 8, name: "Understanding Quadrilaterals" },
  { grade: 8, name: "Data Handling" },
  { grade: 8, name: "Squares and Square Roots" },
  { grade: 8, name: "Cubes and Cube Roots" },
  { grade: 8, name: "Comparing Quantities" },
  { grade: 8, name: "Algebraic Expressions and Identities" },
  { grade: 8, name: "Visualising Solid Shapes" },
  { grade: 8, name: "Mensuration" },
  { grade: 8, name: "Exponents and Powers" },
  { grade: 8, name: "Direct and Inverse Proportions" },
  { grade: 8, name: "Factorisation" },
  { grade: 8, name: "Introduction to Graphs" },
  { grade: 8, name: "Playing with Numbers" },
  // Grade 9
  { grade: 9, name: "Number Systems" },
  { grade: 9, name: "Polynomials" },
  { grade: 9, name: "Coordinate Geometry" },
  { grade: 9, name: "Linear Equations in Two Variables" },
  { grade: 9, name: "Introduction to Euclid's Geometry" },
  { grade: 9, name: "Lines and Angles" },
  { grade: 9, name: "Triangles" },
  { grade: 9, name: "Quadrilaterals" },
  { grade: 9, name: "Circles" },
  { grade: 9, name: "Heron's Formula" },
  { grade: 9, name: "Surface Areas and Volumes" },
  { grade: 9, name: "Statistics" },
  { grade: 9, name: "Probability" },
  // Grade 10
  { grade: 10, name: "Real Numbers" },
  { grade: 10, name: "Polynomials" },
  { grade: 10, name: "Pair of Linear Equations in Two Variables" },
  { grade: 10, name: "Quadratic Equations" },
  { grade: 10, name: "Arithmetic Progressions" },
  { grade: 10, name: "Triangles" },
  { grade: 10, name: "Coordinate Geometry" },
  { grade: 10, name: "Introduction to Trigonometry" },
  { grade: 10, name: "Some Applications of Trigonometry" },
  { grade: 10, name: "Circles" },
  { grade: 10, name: "Areas Related to Circles" },
  { grade: 10, name: "Surface Areas and Volumes" },
  { grade: 10, name: "Statistics" },
  { grade: 10, name: "Probability" },
];

const science: SeedTopic[] = [
  // Grade 6
  { grade: 6, name: "Food: Where Does It Come From?" },
  { grade: 6, name: "Components of Food" },
  { grade: 6, name: "Fibre to Fabric" },
  { grade: 6, name: "Sorting Materials into Groups" },
  { grade: 6, name: "Separation of Substances" },
  { grade: 6, name: "Changes Around Us" },
  { grade: 6, name: "Getting to Know Plants" },
  { grade: 6, name: "Body Movements" },
  { grade: 6, name: "The Living Organisms and Their Surroundings" },
  { grade: 6, name: "Motion and Measurement of Distances" },
  { grade: 6, name: "Light, Shadows and Reflections" },
  { grade: 6, name: "Electricity and Circuits" },
  { grade: 6, name: "Fun with Magnets" },
  { grade: 6, name: "Water" },
  { grade: 6, name: "Air Around Us" },
  { grade: 6, name: "Garbage In, Garbage Out" },
  // Grade 7
  { grade: 7, name: "Nutrition in Plants" },
  { grade: 7, name: "Nutrition in Animals" },
  { grade: 7, name: "Fibre to Fabric" },
  { grade: 7, name: "Heat" },
  { grade: 7, name: "Acids, Bases and Salts" },
  { grade: 7, name: "Physical and Chemical Changes" },
  { grade: 7, name: "Weather, Climate and Adaptations" },
  { grade: 7, name: "Winds, Storms and Cyclones" },
  { grade: 7, name: "Soil" },
  { grade: 7, name: "Respiration in Organisms" },
  { grade: 7, name: "Transportation in Animals and Plants" },
  { grade: 7, name: "Reproduction in Plants" },
  { grade: 7, name: "Motion and Time" },
  { grade: 7, name: "Electric Current and its Effects" },
  { grade: 7, name: "Light" },
  { grade: 7, name: "Water: A Precious Resource" },
  { grade: 7, name: "Forests: Our Lifeline" },
  { grade: 7, name: "Wastewater Story" },
  // Grade 8
  { grade: 8, name: "Crop Production and Management" },
  { grade: 8, name: "Microorganisms: Friend and Foe" },
  { grade: 8, name: "Synthetic Fibres and Plastics" },
  { grade: 8, name: "Materials: Metals and Non-Metals" },
  { grade: 8, name: "Coal and Petroleum" },
  { grade: 8, name: "Combustion and Flame" },
  { grade: 8, name: "Conservation of Plants and Animals" },
  { grade: 8, name: "Cell — Structure and Functions" },
  { grade: 8, name: "Reproduction in Animals" },
  { grade: 8, name: "Reaching the Age of Adolescence" },
  { grade: 8, name: "Force and Pressure" },
  { grade: 8, name: "Friction" },
  { grade: 8, name: "Sound" },
  { grade: 8, name: "Chemical Effects of Electric Current" },
  { grade: 8, name: "Some Natural Phenomena" },
  { grade: 8, name: "Light" },
  { grade: 8, name: "Stars and the Solar System" },
  { grade: 8, name: "Pollution of Air and Water" },
  // Grade 9
  { grade: 9, name: "Matter in Our Surroundings" },
  { grade: 9, name: "Is Matter Around Us Pure?" },
  { grade: 9, name: "Atoms and Molecules" },
  { grade: 9, name: "Structure of the Atom" },
  { grade: 9, name: "The Fundamental Unit of Life" },
  { grade: 9, name: "Tissues" },
  { grade: 9, name: "Diversity in Living Organisms" },
  { grade: 9, name: "Motion" },
  { grade: 9, name: "Force and Laws of Motion" },
  { grade: 9, name: "Gravitation" },
  { grade: 9, name: "Work and Energy" },
  { grade: 9, name: "Sound" },
  { grade: 9, name: "Why Do We Fall Ill?" },
  { grade: 9, name: "Natural Resources" },
  { grade: 9, name: "Improvement in Food Resources" },
  // Grade 10
  { grade: 10, name: "Chemical Reactions and Equations" },
  { grade: 10, name: "Acids, Bases and Salts" },
  { grade: 10, name: "Metals and Non-metals" },
  { grade: 10, name: "Carbon and its Compounds" },
  { grade: 10, name: "Life Processes" },
  { grade: 10, name: "Control and Coordination" },
  { grade: 10, name: "How do Organisms Reproduce?" },
  { grade: 10, name: "Heredity and Evolution" },
  { grade: 10, name: "Light — Reflection and Refraction" },
  { grade: 10, name: "The Human Eye and the Colourful World" },
  { grade: 10, name: "Electricity" },
  { grade: 10, name: "Magnetic Effects of Electric Current" },
  { grade: 10, name: "Sources of Energy" },
  { grade: 10, name: "Our Environment" },
  { grade: 10, name: "Management of Natural Resources" },
];

const socialScience: SeedTopic[] = [
  // Grade 6 — History (Our Pasts I), Geography (The Earth: Our Habitat), Civics
  { grade: 6, name: "History: What, Where, How and When?" },
  { grade: 6, name: "History: From Hunting–Gathering to Growing Food" },
  { grade: 6, name: "History: In the Earliest Cities" },
  { grade: 6, name: "History: Kingdoms, Kings and an Early Republic" },
  { grade: 6, name: "History: New Questions and Ideas" },
  { grade: 6, name: "Geography: The Earth in the Solar System" },
  { grade: 6, name: "Geography: Globe — Latitudes and Longitudes" },
  { grade: 6, name: "Geography: Motions of the Earth" },
  { grade: 6, name: "Geography: Maps" },
  { grade: 6, name: "Geography: Major Landforms of the Earth" },
  { grade: 6, name: "Civics: Understanding Diversity" },
  { grade: 6, name: "Civics: Diversity and Discrimination" },
  { grade: 6, name: "Civics: What is Government?" },
  { grade: 6, name: "Civics: Panchayati Raj" },
  // Grade 7 — Our Pasts II, Our Environment, Social & Political Life II
  { grade: 7, name: "History: Tracing Changes Through a Thousand Years" },
  { grade: 7, name: "History: New Kings and Kingdoms" },
  { grade: 7, name: "History: The Delhi Sultans" },
  { grade: 7, name: "History: The Mughal Empire" },
  { grade: 7, name: "Geography: Environment" },
  { grade: 7, name: "Geography: Inside Our Earth" },
  { grade: 7, name: "Geography: Air" },
  { grade: 7, name: "Geography: Water" },
  { grade: 7, name: "Civics: On Equality" },
  { grade: 7, name: "Civics: Role of the Government in Health" },
  { grade: 7, name: "Civics: Understanding Media" },
  // Grade 8 — Our Pasts III, Resources and Development, Social & Political Life III
  { grade: 8, name: "History: How, When and Where" },
  { grade: 8, name: "History: From Trade to Territory" },
  { grade: 8, name: "History: Ruling the Countryside" },
  { grade: 8, name: "History: When People Rebel — 1857 and After" },
  { grade: 8, name: "Geography: Resources" },
  { grade: 8, name: "Geography: Land, Soil, Water, Natural Vegetation and Wildlife" },
  { grade: 8, name: "Geography: Agriculture" },
  { grade: 8, name: "Geography: Industries" },
  { grade: 8, name: "Civics: The Indian Constitution" },
  { grade: 8, name: "Civics: Understanding Secularism" },
  { grade: 8, name: "Civics: Why Do We Need a Parliament?" },
  // Grade 9 — India & Contemporary World I, Contemporary India I, Democratic Politics I, Economics
  { grade: 9, name: "History: The French Revolution" },
  { grade: 9, name: "History: Socialism in Europe and the Russian Revolution" },
  { grade: 9, name: "History: Nazism and the Rise of Hitler" },
  { grade: 9, name: "Geography: India — Size and Location" },
  { grade: 9, name: "Geography: Physical Features of India" },
  { grade: 9, name: "Geography: Drainage" },
  { grade: 9, name: "Political Science: What is Democracy? Why Democracy?" },
  { grade: 9, name: "Political Science: Constitutional Design" },
  { grade: 9, name: "Economics: The Story of Village Palampur" },
  { grade: 9, name: "Economics: People as Resource" },
  { grade: 9, name: "Economics: Poverty as a Challenge" },
  // Grade 10 — India & Contemporary World II, Contemporary India II, Democratic Politics II, Economic Development
  { grade: 10, name: "History: The Rise of Nationalism in Europe" },
  { grade: 10, name: "History: Nationalism in India" },
  { grade: 10, name: "History: The Making of a Global World" },
  { grade: 10, name: "Geography: Resources and Development" },
  { grade: 10, name: "Geography: Water Resources" },
  { grade: 10, name: "Geography: Agriculture" },
  { grade: 10, name: "Geography: Minerals and Energy Resources" },
  { grade: 10, name: "Political Science: Power Sharing" },
  { grade: 10, name: "Political Science: Federalism" },
  { grade: 10, name: "Economics: Development" },
  { grade: 10, name: "Economics: Sectors of the Indian Economy" },
  { grade: 10, name: "Economics: Money and Credit" },
];

const english: SeedTopic[] = [
  // Grade 6 — Honeysuckle + A Pact with the Sun
  { grade: 6, name: "Honeysuckle: Who Did Patrick's Homework?" },
  { grade: 6, name: "Honeysuckle: How the Dog Found Himself a New Master!" },
  { grade: 6, name: "Honeysuckle: Taro's Reward" },
  { grade: 6, name: "Honeysuckle: An Indian–American Woman in Space: Kalpana Chawla" },
  { grade: 6, name: "Honeysuckle: A Different Kind of School" },
  { grade: 6, name: "A Pact with the Sun (Supplementary Reader)" },
  // Grade 7 — Honeycomb + An Alien Hand
  { grade: 7, name: "Honeycomb: Three Questions" },
  { grade: 7, name: "Honeycomb: A Gift of Chappals" },
  { grade: 7, name: "Honeycomb: The Ashes That Made Trees Bloom" },
  { grade: 7, name: "Honeycomb: The Invention of Vita-Wonk" },
  { grade: 7, name: "An Alien Hand (Supplementary Reader)" },
  // Grade 8 — Honeydew + It So Happened
  { grade: 8, name: "Honeydew: The Best Christmas Present in the World" },
  { grade: 8, name: "Honeydew: The Tsunami" },
  { grade: 8, name: "Honeydew: Glimpses of the Past" },
  { grade: 8, name: "Honeydew: Bepin Choudhury's Lapse of Memory" },
  { grade: 8, name: "It So Happened (Supplementary Reader)" },
  // Grade 9 — Beehive + Moments; Grammar & Writing
  { grade: 9, name: "Beehive: The Fun They Had" },
  { grade: 9, name: "Beehive: The Sound of Music" },
  { grade: 9, name: "Beehive: The Little Girl" },
  { grade: 9, name: "Beehive: A Truly Beautiful Mind" },
  { grade: 9, name: "Moments (Supplementary Reader)" },
  { grade: 9, name: "Grammar and Writing Skills" },
  // Grade 10 — First Flight + Footprints Without Feet; Grammar & Writing
  { grade: 10, name: "First Flight: A Letter to God" },
  { grade: 10, name: "First Flight: Nelson Mandela — Long Walk to Freedom" },
  { grade: 10, name: "First Flight: Two Stories about Flying" },
  { grade: 10, name: "First Flight: From the Diary of Anne Frank" },
  { grade: 10, name: "Footprints Without Feet (Supplementary Reader)" },
  { grade: 10, name: "Grammar and Writing Skills" },
];

// Hindi & Sanskrit are catalogued at the textbook level (see NCERT_TEXTBOOKS
// below); their chapter lists are left to be filled in per edition.
export const NCERT_CURRICULUM: SeedSubject[] = [
  { name: "Mathematics", topics: mathematics },
  { name: "Science", topics: science },
  { name: "Social Science", topics: socialScience },
  { name: "English", topics: english },
  { name: "Hindi", topics: [] },
  { name: "Sanskrit", topics: [] },
];

// ── NCERT textbooks, per subject per grade (in order) ───────────────────────
export interface SeedTextbook {
  subject: string;
  grade: number;
  name: string;
}

export const NCERT_TEXTBOOKS: SeedTextbook[] = [
  // Mathematics — one book per grade.
  ...[6, 7, 8, 9, 10].map((g) => ({ subject: "Mathematics", grade: g, name: "Mathematics" })),
  // Science — one book per grade.
  ...[6, 7, 8, 9, 10].map((g) => ({ subject: "Science", grade: g, name: "Science" })),
  // English — a main reader + a supplementary reader per grade.
  { subject: "English", grade: 6, name: "Honeysuckle" },
  { subject: "English", grade: 6, name: "A Pact with the Sun (Supplementary)" },
  { subject: "English", grade: 7, name: "Honeycomb" },
  { subject: "English", grade: 7, name: "An Alien Hand (Supplementary)" },
  { subject: "English", grade: 8, name: "Honeydew" },
  { subject: "English", grade: 8, name: "It So Happened (Supplementary)" },
  { subject: "English", grade: 9, name: "Beehive" },
  { subject: "English", grade: 9, name: "Moments (Supplementary)" },
  { subject: "English", grade: 10, name: "First Flight" },
  { subject: "English", grade: 10, name: "Footprints Without Feet (Supplementary)" },
  // Social Science — separate History / Geography / Civics (and Pol.Sci +
  // Economics from grade 9) books.
  { subject: "Social Science", grade: 6, name: "Our Pasts – I (History)" },
  { subject: "Social Science", grade: 6, name: "The Earth: Our Habitat (Geography)" },
  { subject: "Social Science", grade: 6, name: "Social and Political Life – I (Civics)" },
  { subject: "Social Science", grade: 7, name: "Our Pasts – II (History)" },
  { subject: "Social Science", grade: 7, name: "Our Environment (Geography)" },
  { subject: "Social Science", grade: 7, name: "Social and Political Life – II (Civics)" },
  { subject: "Social Science", grade: 8, name: "Our Pasts – III (History)" },
  { subject: "Social Science", grade: 8, name: "Resources and Development (Geography)" },
  { subject: "Social Science", grade: 8, name: "Social and Political Life – III (Civics)" },
  { subject: "Social Science", grade: 9, name: "India and the Contemporary World – I (History)" },
  { subject: "Social Science", grade: 9, name: "Contemporary India – I (Geography)" },
  { subject: "Social Science", grade: 9, name: "Democratic Politics – I (Political Science)" },
  { subject: "Social Science", grade: 9, name: "Economics" },
  { subject: "Social Science", grade: 10, name: "India and the Contemporary World – II (History)" },
  { subject: "Social Science", grade: 10, name: "Contemporary India – II (Geography)" },
  { subject: "Social Science", grade: 10, name: "Democratic Politics – II (Political Science)" },
  { subject: "Social Science", grade: 10, name: "Understanding Economic Development (Economics)" },
  // Hindi — main reader (Vasant / Kshitij), workbook (Durva / Kritika), and
  // supplementary readers per grade.
  { subject: "Hindi", grade: 6, name: "Vasant Bhag 1" },
  { subject: "Hindi", grade: 6, name: "Durva Bhag 1" },
  { subject: "Hindi", grade: 6, name: "Bal Ram Katha" },
  { subject: "Hindi", grade: 7, name: "Vasant Bhag 2" },
  { subject: "Hindi", grade: 7, name: "Durva Bhag 2" },
  { subject: "Hindi", grade: 7, name: "Bal Mahabharat Katha" },
  { subject: "Hindi", grade: 8, name: "Vasant Bhag 3" },
  { subject: "Hindi", grade: 8, name: "Durva Bhag 3" },
  { subject: "Hindi", grade: 8, name: "Bharat ki Khoj" },
  { subject: "Hindi", grade: 8, name: "Sanshipt Budhcharit" },
  { subject: "Hindi", grade: 9, name: "Kshitij Bhag 1" },
  { subject: "Hindi", grade: 9, name: "Kritika Bhag 1" },
  { subject: "Hindi", grade: 9, name: "Sparsh Bhag 1" },
  { subject: "Hindi", grade: 9, name: "Sanchayan Bhag 1" },
  { subject: "Hindi", grade: 10, name: "Kshitij Bhag 2" },
  { subject: "Hindi", grade: 10, name: "Kritika Bhag 2" },
  { subject: "Hindi", grade: 10, name: "Sparsh Bhag 2" },
  { subject: "Hindi", grade: 10, name: "Sanchayan Bhag 2" },
  // Sanskrit — Ruchira (6–8), and Shemushi + workbooks (9–10).
  { subject: "Sanskrit", grade: 6, name: "Ruchira Bhag 1" },
  { subject: "Sanskrit", grade: 7, name: "Ruchira Bhag 2" },
  { subject: "Sanskrit", grade: 8, name: "Ruchira Bhag 3" },
  { subject: "Sanskrit", grade: 9, name: "Shemushi Bhag 1" },
  { subject: "Sanskrit", grade: 9, name: "Abhyaswan Sanskritam Bhag 1" },
  { subject: "Sanskrit", grade: 9, name: "Vyakaranavithi" },
  { subject: "Sanskrit", grade: 10, name: "Shemushi Bhag 2" },
  { subject: "Sanskrit", grade: 10, name: "Abhyaswan Sanskritam Bhag 2" },
  { subject: "Sanskrit", grade: 10, name: "Vyakaranavithi" },
];
